### PR TITLE
feature: Better 'install' command output.

### PR DESCRIPTION
**Pull request by eminfedar**
I have tested this one and works well. Also considered the advices. :)

### CODE REVIEW

**Comment by Gama11** [comment]
Is MiB / KiB really better than MB / KB though? I think most people don't really have much of a concept of the former units...

**Comment by back2dos** [comment]
Nitpick: it's [`kB`](https://en.wikipedia.org/wiki/Kilo-).

**Comment by RealyUniqueName** [comment]
I'm too old for MiB/KiB and prefer classic MB/KB naming too.
But aparently MB doesn't mean 2^10 anymore, because HDD manufacturers and developers of desktop environments decided that MB is 10^6.

**Comment by eminfedar** [comment]
So, what should I use, 2^n or 10^n calculation with "MB/KB" tags?

**Comment by haxiomic** [comment]
I think 10^n is the way to go for MB/KB (see wikipedia page https://en.wikipedia.org/wiki/Megabyte)

**Comment by Aurel300** [comment]
@eminfedar I think I'm outvoted here! Sorry for wasting your time on this, but I guess it should read `MB` for multiples of `1000000`, and `kB` (lowercase `k` is more correct) for multiples of `1000`.

**Pull request merged**
