### PR TITLE
Fix for #380

### PR DESCRIPTION
**Pull request by starburst997**
It is indeed possible to write Javascript code inside "releasenote" and get them executed on the website. This fix it. But there might be some other area like "description" / "name"  / "contributors", even license that might be vulnerable???

A simple
```
"releasenote": "Just a normal message <script>console.log('Some evil code');</script>",
```

Inside a haxelib.json is enough.

### CODE REVIEW

**Comment by Simn** [comment]
This is important, injection like that is very embarrassing in 2017...

**Comment by starburst997** [comment]
I'm currently trying to test every possible fields on my dev haxelib and see if there is other vulnerability like this elsewhere.

**Comment by starburst997** [comment]
When using "register" on haxelib, you can get injection on the website with the "Full name"
```
Fullname : Name<script>console.log('full');</script>
```

**Comment by fullofcaffeine** [comment]
Can't we have automatic sanitization on the view layer?

**Comment by starburst997** [comment]
Yeah, I didn't want to go too deep inside the code, but it seems like this is worst than I thought and this would mean htmlEscape everywhere, so might as well get that on the view layer.

**Comment by starburst997** [comment]
Tags are vulnerable to this also

**Comment by starburst997** [comment]
"url" and "description" also

**Comment by fullofcaffeine** [comment]
@starburst997 >EDIT: Btw, what's the template rendering engine used here?

**Comment by starburst997** [comment]
Erazor
https://github.com/ufront/erazor

**Comment by fullofcaffeine** [comment]
@starburst997 I can see an whitelisting approach where all interpolated values are escaped by default. Whatever needs to render actual HTML can then be added to a whitelist somehow (maybe by wrapping it in a call to `htmlSafe()` or something).

I think that would need to be hacked at the erazor level. I don't have time right now (using my lunch time now to answer to this thread) otherwise I'd look. But might be able to do that over the weekend.

**Comment by Simn** [comment]
Thanks for this!

**Pull request merged**
