### PR TITLE
Git dependencies

### PR DESCRIPTION
**Pull request by st3veV**
Git dependencies behavior as discussed in #238 :
- it's now possible to call `haxelib install haxelib.json` and dependencies from the json will be installed
- dependencies can have version in form: `git:<url>#commit-ish`... if so git dependency will be installed, this is possible in both json and hxml definitions
- if `commit-ish` is defined and/or different than one already installed from same json/hxml (ie. because of dependency of dependency) user is prompted to confirm overwriting existing git version

### CODE REVIEW

**Comment by andyli** [comment]
Thanks. Would you take a look at the failed test and try to fix it?
```
Command: haxe [client_tests.hxml]
Class: tests.TestSemVer ...
Class: tests.TestData .E.......
Class: tests.TestRemoveSymlinks .
Class: tests.TestRemoveSymlinksBroken .
Class: tests.TestHg ...........
Class: tests.TestGit ...........
Class: tests.TestVcsNotFound ....
Class: tests.TestInstall ..
* tests.TestData::testReadDataWithoutCheck()
ERR: exception thrown : Invalid field access : length
Called from StringTools::startsWith line 142
Called from haxelib._Data.Dependencies_Impl_::toArray line 83
Called from haxelib.Data::readData line 339
Called from tests.TestData::testReadDataWithoutCheck line 237
Called from a C function
Called from haxe.unit.TestRunner::runCase line 115
FAILED 42 tests, 1 failed, 41 success
Command exited with 1 in 55s: haxe [client_tests.hxml]
```

**Comment by st3veV** [comment]
Fixed.

**Comment by ibilon** [comment]
Hey, thanks for the contribution.

Could you add a check that vcs dependencies aren't allow when submitting to haxelib?

> if commit-ish is defined and/or different than one already installed from same json/hxml (ie. because of dependency of dependency) user is prompted to confirm overwriting existing git version

Not sure I fully get what that means, you can't have two branch of the same repository used as deps by different libs/project?

**Comment by st3veV** [comment]
Yep, the check makes sense. I'll look at it.

>Not sure I fully get what that means, you can't have two branch of the same repository used as deps by different libs/project?

Correct. In the discussion for #238 it was decided to not bother with this and support just one because it already brings quite a lot of value (https://github.com/HaxeFoundation/haxelib/issues/238#issuecomment-223231264 and https://github.com/HaxeFoundation/haxelib/issues/238#issuecomment-224905389).

**Comment by st3veV** [comment]
So I did some digging through the code and testing and there already is a "check"... submit fails with ie.: `Error: git:https://github.com/fzzr-/hx.signal.git is not a valid version string` because the JSON is being validated. In my opinion the error descriptive enough and submit is failing so it behaves as expected but I'm open to different opinions.

**Comment by ibilon** [comment]
The error message could be improved but it's still descriptive enough.

@nadako I haven't tried it yet but the design and code are good, what do you think?

**Comment by nadako** [comment]
lgtm, ship it!

**Pull request merged**
