### PR TITLE
New website by @jasononeil

### PR DESCRIPTION
**Pull request by nadako**
This is [the new website branch](https://github.com/jasononeil/haxelib/tree/feature/newsite) by @jasononeil, squashed and rebased on latest master, if noone objects, I'll merge it into master and let's continue work here.

cc @ncannasse @andyli

### CODE REVIEW

**Comment by nadako** [comment]
Note that this is kind of blocker for the further haxelib work, since we would like to refactor things, but we definitely should start doing that after merging this PR, or else it'll be a pain.

**Comment by Simn** [comment]
I'll risk it!

**Comment by nadako** [comment]
Okay, let's roll :)

**Comment by Simn** [comment]
Go for it!

Let me know if you need anything. Anything that doesn't involve actually looking at this codebase!

**Pull request merged**
