### PR TITLE
Location-independent haxelib runscript.

### PR DESCRIPTION
**Pull request by ioga**
One can create a symlink to that script and run it from any place
without bothering about proper classpath etc.

### CODE REVIEW

**Comment by nadako** [comment]
@andyli is this still relevant? I'm on Windows, so I can't check this out, but I think haxe's `make install` generates this script nowadays.

**Comment by ioga** [comment]
Yes, the issue is still there. In https://github.com/HaxeFoundation/haxe/blob/development/Makefile#L114 one can currently see:
`echo "exec haxe -cp $(INSTALL_LIB_DIR)/extra/haxelib_src/src --run haxelib.client.Main \"\$$@\"" >> $(INSTALL_BIN_DIR)/haxelib`

i.e. the installation directory is hardcoded into haxelib script, and therefore you cannot move it around, and staged installs mentioned in https://github.com/HaxeFoundation/haxe/issues/2850 still won't work.

This particular changeset (as well as some part of haxe#2850) is probably outdated though since it's almost 2 years old.

**Comment by andyli** [comment]
The "haxelib script" is problematic in many ways.. So I'm very tempted to remove it and use the good old nekotools booted haxelib instead. But I have to figure out this implication to the selfupdate thing... which is another source of headache to me.

**Comment by nadako** [comment]
See #172 as @ibilon proposed a way to handle selfupdate where we can just keep bundled haxelib as a `nekoboot`ed executable.

**Comment by nadako** [comment]
I'll close this as we seem to be moving away from shell script to nekobooted executable (see #172 and #284)

**Pull request closed without merging**
