### PR TITLE
Only use haxelib package globally

### PR DESCRIPTION
**Pull request by ibilon**
4th point of #293

this prevent haxelib to be use/load/updated/installed/run in a local repository

### CODE REVIEW

**Comment by nadako** [comment]
Let me do that, I was in-progress, but I got distracted by @RobDangerous live stream https://www.twitch.tv/robdangerous :)

**Comment by nadako** [comment]
Actually, I don't like neither my changes nor yours (they are very similar). Haxelib code is ugly enough already :)

How about we not restrict project-local haxelib installations, but only use one from the global repository and point user that he needs to add `--global` to update haxelib.

**Comment by ibilon** [comment]
Special cases are never pretty,
as long as we don't load it and if we modify the notification it should be ok.

**Comment by nadako** [comment]
I did that in b88a81bd0649a235f3fd10e68a189ab885069c0e.
We can revisit this when we'll be refactoring stuff, but this should be sufficient for now.

**Pull request closed without merging**
